// import { Geist, Geist_Mono } from "next/font/google";


import "./globals.css";
import Navbar from "./Navbar";
import Footer from "./Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Welcome to your own home",
  description: "Generated by create Hussien Mohamed",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <br/>
        {children}
       < Footer/>
      </body>
    </html>
  );
}
